--- 
title: "Un petit manual de psychologie contemporaine à destination de ceux qui souffrent"
author: "Arnaud Passé"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
#output: bookdown::gitbook
documentclass: book
#bibliography: [book.bib, packages.bib]
#biblio-style: apalike
#link-citations: yes
github-repo: chabefer/MANUAL
description: "Un livre open source et collaboratif."
---

# Introduction {-}

Ce livre est une série de notes prises pour documenter ma progression dans la compréhension des enseignements de la psychologie contemporaine, notamment pour ce qui a trait à la résolution des souffrances psychologiques.

Les souffrances psychologiques sont une des sources majeures de mal-être dans les sociétés développées contemporaines.
Je développe dans mes romans des exemples de la souffrance psychologique et de ses résultats sur la vie des gens.
Dans ce petit manuel, je compile ce que j'ai compris et ce que j'ai trouvé utile dans les enseignement de la psychologie contemporaine pour résoudre les souffrances psychologiques.
J'aborde notamment les approches comportementale et cognitive, la théorie de la personnalité et la science de la mesure du bien-être.


